version: '3.9'

services:
  nest:
    command: /bin/bash -c "while sleep 1000; do :; done & yarn start:dev"
    ports:
      - 3000:3000 # nest
      - 5555:5555 # prisma studio
      - 9229:9229 # debugger
