version: '3.9'
services:
  nest:
    container_name: nest
    build:
      context: ..
      dockerfile: .docker/dev.Dockerfile
    volumes:
      - ../.:/app:cached
      - nestmods:/app/node_modules:cached
    ports:
      - 3000:3000
    restart: unless-stopped
    tty: true
    stdin_open: true

  psql:
    container_name: psql
    image: postgres:15
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - psqldata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  nestmods:
  psqldata:
